QUEST_KEEP_KAREF_RESOLVE_CORINTH = 0
QUEST_KEEP_DEFEND = 1
QUEST_KEEP_TENKITS_RING = 2
QUEST_KEEP_QUORIS_SUMMON_1 = 3
QUEST_KEEP_QUORIS_CHALICE = 4

RUMOR_KEEP_KAREF_WEST_CAVES_MENTIONED = 0
RUMOR_KEEP_SHANIA_CAN_DECIPHER = 1